export const books = [
    {"book_id": 1, "title": "Gilead", "author": "Marilynne Robinson", "ISBN": "9780002005883", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 2, "title": "Spider's Web", "author": "Charles Osborne;Agatha Christie", "ISBN": "9780002261982", "category": "Mystery", "image_url": "http://books.google.com/books/content?id=gA5GPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 3, "title": "The One Tree", "author": "Stephen R. Donaldson", "ISBN": "9780006163831", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=OmQawwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 4, "title": "Rage of angels", "author": "Sidney Sheldon", "ISBN": "9780006178736", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=FKo2TgANz74C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 5, "title": "An Autobiography", "author": "Agatha Christie", "ISBN": "9780006353287", "category": "Authors, English", "image_url": "http://books.google.com/books/content?id=c49GQwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 6, "title": "Master of the Game", "author": "Sidney Sheldon", "ISBN": "9780006472612", "category": "Adventure", "image_url": "http://books.google.com/books/content?id=TkTYp-Tp6_IC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 7, "title": "If Tomorrow Comes", "author": "Sidney Sheldon", "ISBN": "9780006479673", "category": "Adventure", "image_url": "http://books.google.com/books/content?id=l2tBi_jLuk8C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 8, "title": "Assassin's Apprentice", "author": "Robin Hobb", "ISBN": "9780006480099", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=qTaGQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 9, "title": "Warhost of Vastmark", "author": "Janny Wurts", "ISBN": "9780006482079", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=uOL0fpS9WZkC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 10, "title": "The Once and Future King", "author": "Terence Hanbury White", "ISBN": "9780006483014", "category": "Romances", "image_url": "http://books.google.com/books/content?id=Jx6BvgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 11, "title": "Murder in LaMut", "author": "Raymond E. Feist;Joel Rosenberg", "ISBN": "9780006483892", "category": "Adventure", "image_url": "http://books.google.com/books/content?id=I2jbBlMHlAMC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 12, "title": "Jimmy the Hand", "author": "Raymond E. Feist;S. M. Stirling", "ISBN": "9780006483908", "category": "Fantasy fiction", "image_url": "http://books.google.com/books/content?id=hV4-oITYFN8C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 13, "title": "Witness for the Prosecution & Selected Plays", "author": "Agatha Christie", "ISBN": "9780006490456", "category": "Drama", "image_url": "http://books.google.com/books/content?id=_9u7AAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 14, "title": "The Little House", "author": "Philippa Gregory", "ISBN": "9780006496434", "category": "Country life", "image_url": "http://books.google.com/books/content?id=rbvUPps9vKsC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 15, "title": "Mystical Paths", "author": "Susan Howatch", "ISBN": "9780006496878", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=by4ytBy63o0C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 16, "title": "Glittering Images", "author": "Susan Howatch", "ISBN": "9780006496892", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=rDHbn0ORKhQC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 17, "title": "Lirael", "author": "Garth Nix", "ISBN": "9780007137336", "category": "Fantasy fiction", "image_url": "http://books.google.com/books/content?id=sDzU8TpKvQAC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 18, "title": "Tales from the Perilous Realm", "author": "John Ronald Reuel Tolkien", "ISBN": "9780007149124", "category": "Fairy tales", "image_url": "http://books.google.com/books/content?id=Wla7NwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 19, "title": "Breaking Open the Head", "author": "Daniel Pinchbeck", "ISBN": "9780007149612", "category": "Hallucinogenic drugs", "image_url": "http://books.google.com/books/content?id=QIMaviqqoQoC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 20, "title": "The Yiddish Policemen's Union", "author": "Michael Chabon", "ISBN": "9780007149827", "category": "Fiction", "image_url": "http://books.google.com/books/content?id=-reD1g77BfsC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 21, "title": "Beware, Princess Elizabeth", "author": "Carolyn Meyer", "ISBN": "9780007150304", "category": "Children's stories", "image_url": "http://books.google.com/books/content?id=wPBpR4AFNJ0C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 22, "title": "The Family Way", "author": "Tony Parsons", "ISBN": "9780007151240", "category": "Parenthood", "image_url": "http://books.google.com/books/content?id=dJEIxdYmnU8C&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 23, "title": "Endless Night", "author": "Agatha Christie", "ISBN": "9780007151677", "category": "FICTION", "image_url": "http://books.google.com/books/content?id=kY1wuNfgmFQC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 24, "title": "How to be Alone", "author": "Jonathan Franzen", "ISBN": "9780007153589", "category": "Literary Collections", "image_url": "http://books.google.com/books/content?id=ozVWaXd9xvwC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
,{"book_id": 25, "title": "The Mysterious Mr. Quin", "author": "Agatha Christie", "ISBN": "9780007154845", "category": "Mystery", "image_url": "http://books.google.com/books/content?id=n0aMDV7Lm4sC&printsec=frontcover&img=1&zoom=1&source=gbs_api", "total_copies": 1, "available_copies": 1}
]